### ISSUE TITLE
Can it work in bridge mode ?

### ISSUE THREAD

**Issue by hot22shot** [addrum/synology-notifications#1]
Hello,

I successfully installed and configured the container in host mode (and thank you for sharing your development), but I was wondering if it could also work in a network bridge mode ?
Could you publish some docker-compose example ?

Regards

**Comment by addrum** [comment]
There's no reason it shouldn't work in bridge mode afaik; in fact I have it running in bridge mode on my own system. Just make sure you map port `8686` to one that's not already in use on the host.

**Comment by hot22shot** [comment]
Yes, that's what I did.
Well it is working now in host mode on the 8686 port, so I suspect it must be some network issue on my end.
